import { Pitch, PitchName, Scale, Key } from "./index"
import assert from "assert"


const c = PitchName.parse("C")
assert.equal(c.letter, 0)
assert.equal(c.accidental, 0)
assert.equal(c.name, "C")
assert.equal(c.midiPitch, 0)
assert.equal(c.pitchClass, 0)

const fb = PitchName.parse("Fb")
assert.equal(fb.letter, 3)
assert.equal(fb.accidental, -1)
assert.equal(fb.name, "F♭")
assert.equal(fb.midiPitch, 4)
assert.equal(fb.pitchClass, 4)

const bsss = PitchName.parse("B###")
assert.equal(bsss.letter, 6)
assert.equal(bsss.accidental, 3)
assert.equal(bsss.name, "B♯♯♯")
assert.equal(bsss.midiPitch, 14)
assert.equal(bsss.pitchClass, 2)

const d5 = Pitch.parse("D5")
assert.equal(d5.name, "D5")
assert.equal(d5.pitchName.name, "D")
assert.equal(d5.midiPitch, 62)
assert.equal(d5.pitchClass, 2)

const cMajorKey = Key.parse("C Major")
assert.equal(cMajorKey.tonic.name, "C")
assert.equal(cMajorKey.scale.name, "Major")
assert.equal(cMajorKey.degreeForPitch(c), 0)
assert.equal(cMajorKey.degreeForPitch(fb), 2)
assert.equal(cMajorKey.degreeForPitch(bsss), 8)
assert.equal(cMajorKey.degreeForPitch(d5), 5 * 7 + 1)
assert.equal(cMajorKey.pitchNameForPitch(c).name, "C")
assert.equal(cMajorKey.pitchNameForPitch(fb).name, "E")
assert.equal(cMajorKey.pitchNameForPitch(bsss).name, "D")
assert.equal(cMajorKey.pitchNameForPitch(d5).name, "D")
assert.equal(cMajorKey.pitchForDegree(0), 0)
assert.equal(cMajorKey.pitchForDegree(4), 7)
assert.equal(cMajorKey.pitchForDegree(6), 11)

const fMinorKey = Key.parse("F Minor")
assert.equal(fMinorKey.tonic.name, "F")
assert.equal(fMinorKey.scale.name, "Natural Minor")
assert.equal(fMinorKey.degreeForPitch(c), -3)
assert.equal(fMinorKey.degreeForPitch(fb), -0.5)
assert.equal(fMinorKey.degreeForPitch(bsss), 5.5)
assert.equal(fMinorKey.degreeForPitch(d5), 4 * 7 + 5.5)
assert.equal(fMinorKey.pitchNameForPitch(c).name, "C")
assert.equal(fMinorKey.pitchNameForPitch(fb).name, "E")
assert.equal(fMinorKey.pitchNameForPitch(bsss).name, "D")
assert.equal(fMinorKey.pitchNameForPitch(d5).name, "D")
assert.equal(fMinorKey.pitchForDegree(0), 5)
assert.equal(fMinorKey.pitchForDegree(4), 12)
assert.equal(fMinorKey.pitchForDegree(6), 15)